name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm test

  Dewo:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Datadog Synthetic Tests
        uses: DataDog/synthetics-ci-github-action@v2.0.0
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          app_key: ${{ secrets.DD_APP_KEY }}
          datadog_site: "us5.datadoghq.com"
          public_ids: |
            rvr-ai5-jwz 

  medico:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Datadog Synthetic Tests
        uses: DataDog/synthetics-ci-github-action@v2.0.0
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          app_key: ${{ secrets.DD_APP_KEY }}
          datadog_site: "us5.datadoghq.com"
          public_ids: |
            mfh-mxc-59t

  butterfly:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Datadog Synthetic Tests
        uses: DataDog/synthetics-ci-github-action@v2.0.0
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          app_key: ${{ secrets.DD_APP_KEY }}
          datadog_site: "us5.datadoghq.com"
          public_ids: |
            dss-kks-zzs

  resume:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Datadog Synthetic Tests
        uses: DataDog/synthetics-ci-github-action@v2.0.0
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          app_key: ${{ secrets.DD_APP_KEY }}
          datadog_site: "us5.datadoghq.com"
          public_ids: |
            zie-r6u-bvk